Running in wrapper mode for '53'

Running python job.

[name: "CPU-QUOTA"
int_val: 65
int_val: 65
int_val: 56
int_val: 75
int_val: 50
int_val: 5
int_val: 74
, name: "DISK"
int_val: 25
int_val: 8
int_val: 7
int_val: 38
int_val: 7
int_val: 22
int_val: 7
, name: "MEMORY"
int_val: 14
int_val: 6
int_val: 27
int_val: 8
int_val: 15
int_val: 14
int_val: 27
, name: "NET"
int_val: 37
int_val: 9
int_val: 10
int_val: 35
int_val: 37
int_val: 21
int_val: 14
]
The paramters are {u'CPU-QUOTA': array([65, 65, 56, 75, 50,  5, 74]), u'NET': array([37,  9, 10, 35, 37, 21, 14]), u'DISK': array([25,  8,  7, 38,  7, 22,  7]), u'MEMORY': array([14,  6, 27,  8, 15, 14, 27])}
{'13.56.14.158': ['haproxy', 'node-app', 'mongo'], '18.144.43.31': ['node-app', 'mongo']}
----------------------------------------
Problem running the job:
(<class 'paramiko.ssh_exception.BadAuthenticationType'>, BadAuthenticationType('Bad authentication type', [u'publickey']), <traceback object at 0x7fd41b752128>)
Traceback (most recent call last):
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 42, in job_runner
    elif job.language == PYTHON: run_python_job(job)
  File "/home/ubuntu/throttlebot/src/spearmint/spearmint/runner.py", line 142, in run_python_job
    result = module.main(job.id, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 104, in main
    return explore_spearmint(workload_config, params)
  File "/home/ubuntu/throttlebot/src/spearmint/bayOptSearch/bayOpt.py", line 147, in explore_spearmint
    client = re.get_client(machine)
  File "/home/ubuntu/throttlebot/src/remote_execution.py", line 6, in get_client
    client.connect(ip, username="quilt", password="")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
None
----------------------------------------
Job file reloaded.
Could not find value in output file.
Job failed in 0.45 seconds.
